[package]
name = "qb_defender"
version = "0.3.0"
edition = "2024"

[workspace.dependencies]
qb_sdk = { path = "qb_sdk" }

[dependencies]
tokio = { version = "1.50.0", features = ["full"] }
clap = { version = "4.6.0", features = ["derive"] }

tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = [
    "env-filter",
    "fmt",
    "time",
] }
tracing-appender = "0.2.4"
time = { version = "0.3.47", features = ["formatting", "macros"] }

chrono = "0.4.44"
thiserror = "2.0.18"

ip_network = { version = "0.4.1" }
qb_sdk = { workspace = true }
