[package]
name = "qb_defender"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
reqwest = { version = "0.12.18", features = ["json"] }
tokio = { version = "1.45.1", features = ["full"] }