[package]
name = "qb_sdk"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
reqwest = "0.12.18"
serde_json = "1.0.140"
tokio = "1.45.1"
ip_network = { version = "0.4.1" }
command = { workspace = true }
log = { workspace = true }