name: Publish

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    strategy:
      matrix:
        include:
          - rid: win-x86_64
            os: windows-latest
            toolchain: x86_64-pc-windows-msvc
          - rid: macos-x86_64
            os: macos-latest
            toolchain: x86_64-apple-darwin
          - rid: macos-aarch64
            os: macos-latest
            toolchain: aarch64-apple-darwin
          - rid: linux-x86_64
            os: ubuntu-latest
            toolchain: x86_64-unknown-linux-gnu
          - rid: linux-i686
            os: ubuntu-latest
            toolchain: i686-unknown-linux-gnu
          - rid: linux-aarch64
            os: ubuntu-latest
            toolchain: aarch64-unknown-linux-gnu
          - rid: linux-arm
            os: ubuntu-latest
            toolchain: arm-unknown-linux-musleabi
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install toolchain
      run: |
        rustup target add ${{ matrix.toolchain }}

    - name: Install openssl
      run: |
        sudo apt-get update
        sudo apt-get install libssl-dev:i386
    
    - name: Build
      run: |
        cargo build --target ${{ matrix.toolchain }} --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.rid}}-bundle
        path: ./target/release/qb_defender${{ startsWith(matrix.rid, 'win') && '.exe' || '' }}
        if-no-files-found: error
