name: Publish

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    strategy:
      matrix:
        rid:
          - win
          - macos
          - linux
    runs-on: ${{ startsWith(matrix.rid, 'win') && 'windows-latest' || startsWith(matrix.rid, 'macos') && 'macos-latest' || 'ubuntu-latest' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: |
        cargo build --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.rid}}-bundle
        path: ./target/release/qb_defender${{ startsWith(matrix.rid, 'win') && '.exe' || '' }}
        if-no-files-found: error
