name: Publish

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build-win-x64:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install x86_64-pc-windows-msvc toolchain
      run: |
        rustup target add x86_64-pc-windows-msvc

    - name: Build
      run: |
        cargo build --release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: win-x64
        path: ./target/release/qb_defender.exe
        if-no-files-found: error
