name: Publish

on:
  workflow_dispatch:

defaults:
  run:
    shell: pwsh

jobs:
  build:
    strategy:
      matrix:
        include:
          #- rid: win-x86_64
          #  host_os: windows-latest
          #  toolchain: x86_64-pc-windows-msvc
          #- rid: macos-x86_64
          #  host_os: macos-latest
          #  toolchain: x86_64-apple-darwin
          #- rid: macos-aarch64
          #  host_os: macos-latest
          #  toolchain: aarch64-apple-darwin
          - rid: linux-x86_64
            host_os: ubuntu-latest
            toolchain: x86_64-unknown-linux-gnu
          - rid: linux-aarch64
            host_os: ubuntu-latest
            toolchain: aarch64-unknown-linux-gnu
    runs-on: ${{ matrix.host_os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup rust
      uses: dtolnay/rust-toolchain@stable
    
    - name: Install target toolchain
      run: |
        rustup target add ${{ matrix.toolchain }}
    
    - name: Install openssl  
      if: ${{ matrix.rid == 'linux-x86_64' }}
      run: |
        sudo apt update
        sudo apt install libssl-dev pkg-config
    
    - name: Install dependencies
      if: ${{ matrix.rid == 'linux-aarch64' }}
      run: |
        sudo apt update
        sudo apt install gcc-aarch64-linux-gnu libc6-dev-arm64-cross

    - name: Create cargo config file
      if: ${{ matrix.rid == 'linux-aarch64' }}
      run: |
        mkdir .cargo
        "[target.aarch64-unknown-linux-gnu]`nlinker = `"aarch64-linux-gnu-gcc`"" > .cargo/config.toml
    
    - name: Build
      run: |
        cargo build --target ${{ matrix.toolchain }} --release
      env:
        OPENSSL_DIR: OPENSSL_DIR=/usr/lib/x86_64-linux-gnu
        OPENSSL_INCLUDE_DIR: /usr/include/openssl
        OPENSSL_LIB_DIR: /usr/lib/x86_64-linux-gnu

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{matrix.rid}}-bundle
        path: ./target/${{ matrix.toolchain }}/release/qb_defender${{ startsWith(matrix.rid, 'win') && '.exe' || '' }}
        if-no-files-found: error
